//NOTE OBJECTS ARE HERE FOR STUBS! THEY ARE JUST SO THE ROOMS COMPILE!
#pragma once

//null sprite (its really long to make sure no one uses it in gm lol)
#define JUOEDESBGFIUFDSVIUFSDVBSAOPDSFIGHSDUIOGFSDIUFDSGFDSIUPFDSIFSDOPFSDAFSDASPFADOPSJSDJOIHFSDISFDOHIJUOEDESBGFIUFDSVIUFSDVBSAOPDSFIGHSDUIOGFSDIUFDSGFDSIUPFDSIFSDOPFSDAFSDASPFADOPSJSDJOIH 0
